In [37]:
import geopandas as gpd
import pandas as pd
import numpy as np

In [38]:
DEFAULT_CRS = "EPSG:4326"

In [39]:

hex_sp = gpd.read_file("data/shapeFiles/GRIDS_H3_SP_RES10") 


# Transform the CRS to EPSG:31983
hex_sp = hex_sp.to_crs(DEFAULT_CRS)
hex_sp.head()

            id_hex                                           geometry
0  8aa8100c3257fff  POLYGON ((-46.63592 -23.53032, -46.63664 -23.5...
1  8aa8100d2447fff  POLYGON ((-46.53650 -23.53972, -46.53722 -23.5...
2  8aa8100e1637fff  POLYGON ((-46.66886 -23.59437, -46.66958 -23.5...
3  8aa8100f0827fff  POLYGON ((-46.59115 -23.61353, -46.59187 -23.6...
4  8aa81010ec07fff  POLYGON ((-46.65231 -23.83331, -46.65303 -23.8...

# IPTU Lotes

In [40]:
iptu_lotes = gpd.read_parquet('data/raw/iptu_por_lotes_2020.parquet')

In [41]:
iptu_lotes.crs

<Projected CRS: EPSG:31983>
Name: SIRGAS 2000 / UTM zone 23S
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: Brazil - between 48°W and 42°W, northern and southern hemispheres, onshore and offshore.
- bounds: (-48.0, -33.5, -42.0, 5.13)
Coordinate Operation:
- name: UTM zone 23S
- method: Transverse Mercator
Datum: Sistema de Referencia Geocentrico para las AmericaS 2000
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [42]:
iptu_lotes.head()

,sqlc,sq,agregado,ano,Quantidade de Unidades,Quantidade de Unidades Condominiais,Tamanho Médio da Unidade Condominial,Tamanho médio dos Terrenos,Área Total dos lotes,Área Total Ocupada,...,Residencial horizontal Alto (qt),Comercial vertical Baixo (qt),Comercial vertical Médio (qt),Comercial vertical Alto (qt),Comercial horizontal Baixo (qt),Comercial horizontal Alto (qt),Comercial horizontal Médio (qt),Terreno (qt),Outros Usos (qt),geometry
0,242002000100,242002,False,2020.0,1,0,NaN,20290.0,20290.0,1344.0,...,0,0,0,0,0,0,0,0,0,"POLYGON ((352627.219 7390910.667, 352619.638 7..."
1,232011019100,232011,False,2020.0,1,0,NaN,125.0,125.0,0.0,...,0,0,0,0,0,0,0,1,0,"POLYGON ((351203.436 7392904.939, 351177.197 7..."
2,232011019000,232011,False,2020.0,1,0,NaN,125.0,125.0,0.0,...,0,0,0,0,0,0,0,1,0,"POLYGON ((351203.436 7392904.939, 351201.939 7..."
3,242001000100,242001,False,2020.0,1,0,NaN,175504.0,175504.0,20423.0,...,0,0,0,0,0,0,0,0,0,"POLYGON ((352675.753 7391791.239, 352679.713 7..."
4,145059015800,145059,False,2020.0,1,0,NaN,150.0,150.0,0.0,...,0,0,0,0,0,0,0,1,0,"POLYGON ((350124.724 7393733.368, 350124.724 7..."

In [43]:
print(list(iptu_lotes.columns))

['sqlc', 'sq', 'agregado', 'ano', 'Quantidade de Unidades', 'Quantidade de Unidades Condominiais', 'Tamanho Médio da Unidade Condominial', 'Tamanho médio dos Terrenos', 'Área Total dos lotes', 'Área Total Ocupada', 'Área Total Construída', 'Valor Total dos Terrenos', 'Valor Total das Construções', 'CA médio', 'TO médio', 'CA médio em lotes condominiais', 'TO médio em lotes condominiais', 'CA médio em lotes não condominiais', 'TO médio em lotes não condominiais', 'Comprimento Médio da Testada', 'Número médio de Pavimentos', 'Fator de obsolecência médio', 'Residencial vertical Baixo (m2)', 'Residencial vertical Médio (m2)', 'Residencial vertical Alto (m2)', 'Residencial horizontal Baixo (m2)', 'Residencial horizontal Médio (m2)', 'Residencial horizontal Alto (m2)', 'Comercial vertical Baixo (m2)', 'Comercial vertical Médio (m2)', 'Comercial vertical Alto (m2)', 'Comercial horizontal Baixo (m2)', 'Comercial horizontal Alto (m2)', 'Comercial horizontal Médio (m2)', 'Terreno (m2)', 'Outros Usos (m2)', 'Residencial vertical Baixo (qt)', 'Residencial vertical Médio (qt)', 'Residencial vertical Alto (qt)', 'Residencial horizontal Baixo (qt)', 'Residencial horizontal Médio (qt)', 'Residencial horizontal Alto (qt)', 'Comercial vertical Baixo (qt)', 'Comercial vertical Médio (qt)', 'Comercial vertical Alto (qt)', 'Comercial horizontal Baixo (qt)', 'Comercial horizontal Alto (qt)', 'Comercial horizontal Médio (qt)', 'Terreno (qt)', 'Outros Usos (qt)', 'geometry']

In [69]:
iptu_lotes[iptu_lotes['sqlc'] == '170041007100']

,sqlc,sq,agregado,ano,Quantidade de Unidades,Quantidade de Unidades Condominiais,Tamanho Médio da Unidade Condominial,Tamanho médio dos Terrenos,Área Total dos lotes,Área Total Ocupada,...,Comercial vertical Baixo (qt),Comercial vertical Médio (qt),Comercial vertical Alto (qt),Comercial horizontal Baixo (qt),Comercial horizontal Alto (qt),Comercial horizontal Médio (qt),Terreno (qt),Outros Usos (qt),geometry,qnt_unidades_residencias
234350,170041007100,170041,False,2020.0,1,0,NaN,550.0,550.0,155.0,...,0,0,0,0,0,0,0,0,"POLYGON ((324114.427 7386165.192, 324116.160 7...",1

In [44]:
iptu_lotes['qnt_unidades_residencias'] = iptu_lotes[[item for item in list(iptu_lotes.columns) if ('residencial' in item.lower() and 'qt' in item.lower())]].sum(axis=1)

In [45]:
iptu_lotes_final = iptu_lotes[['sqlc', 'qnt_unidades_residencias', 'geometry']]

In [46]:
iptu_lotes_final['qnt_unidades_residencial_m2'] = iptu_lotes_final['qnt_unidades_residencias'] / (iptu_lotes_final.to_crs("EPSG:5641").area)

/opt/anaconda3/envs/scriptsMestrado/lib/python3.12/site-packages/geopandas/geodataframe.py:1528: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [47]:
iptu_lotes_final.head()

,sqlc,qnt_unidades_residencias,geometry,qnt_unidades_residencial_m2
0,242002000100,0,"POLYGON ((352627.219 7390910.667, 352619.638 7...",0.0
1,232011019100,0,"POLYGON ((351203.436 7392904.939, 351177.197 7...",0.0
2,232011019000,0,"POLYGON ((351203.436 7392904.939, 351201.939 7...",0.0
3,242001000100,0,"POLYGON ((352675.753 7391791.239, 352679.713 7...",0.0
4,145059015800,0,"POLYGON ((350124.724 7393733.368, 350124.724 7...",0.0

# Intersecção

In [48]:
if iptu_lotes_final.crs != DEFAULT_CRS:
    iptu_lotes_final = iptu_lotes_final.to_crs(DEFAULT_CRS)
if hex_sp.crs != DEFAULT_CRS:
    hex_sp = hex_sp.to_crs(DEFAULT_CRS)

In [49]:
iptu_lotes_join_h3 =  iptu_lotes_final.overlay(hex_sp[['id_hex', 'geometry']], how='intersection')

/opt/anaconda3/envs/scriptsMestrado/lib/python3.12/site-packages/geopandas/geodataframe.py:2475: UserWarning: `keep_geom_type=True` in overlay resulted in 4 dropped geometries of different geometry types than df1 has. Set `keep_geom_type=False` to retain all geometries
  return geopandas.overlay(

In [50]:
iptu_lotes_join_h3.head()

,sqlc,qnt_unidades_residencias,qnt_unidades_residencial_m2,id_hex,geometry
0,242002000100,0,0.0,8aa81009ab37fff,"POLYGON ((-46.44510 -23.58430, -46.44507 -23.5..."
1,242002000100,0,0.0,8aa81009a84ffff,"POLYGON ((-46.44449 -23.58426, -46.44449 -23.5..."
2,242002000100,0,0.0,8aa810098497fff,"POLYGON ((-46.44432 -23.58566, -46.44440 -23.5..."
3,242002000100,0,0.0,8aa81009a867fff,"POLYGON ((-46.44379 -23.58534, -46.44398 -23.5..."
4,242002000100,0,0.0,8aa81009a86ffff,"POLYGON ((-46.44440 -23.58552, -46.44454 -23.5..."

In [51]:
iptu_lotes_join_h3[iptu_lotes_join_h3['sqlc'] == '005076017300']

,sqlc,qnt_unidades_residencias,qnt_unidades_residencial_m2,id_hex,geometry
2272153,005076017300,0,0.0,8aa8100c0747fff,"POLYGON ((-46.62905 -23.55272, -46.62906 -23.5..."
2272154,005076017300,0,0.0,8aa8100c074ffff,"POLYGON ((-46.62910 -23.55261, -46.62916 -23.5..."
2272155,005076017300,0,0.0,8aa8100c075ffff,"POLYGON ((-46.62898 -23.55257, -46.62897 -23.5..."

## Krigatem simples e Agrupar

In [52]:
iptu_lotes_join_h3['qnt_unidades_residencias']  = iptu_lotes_join_h3['qnt_unidades_residencial_m2'] * (iptu_lotes_join_h3.to_crs("EPSG:5641").area)

In [53]:
iptu_lotes_join_h3.head()

,sqlc,qnt_unidades_residencias,qnt_unidades_residencial_m2,id_hex,geometry
0,242002000100,0.0,0.0,8aa81009ab37fff,"POLYGON ((-46.44510 -23.58430, -46.44507 -23.5..."
1,242002000100,0.0,0.0,8aa81009a84ffff,"POLYGON ((-46.44449 -23.58426, -46.44449 -23.5..."
2,242002000100,0.0,0.0,8aa810098497fff,"POLYGON ((-46.44432 -23.58566, -46.44440 -23.5..."
3,242002000100,0.0,0.0,8aa81009a867fff,"POLYGON ((-46.44379 -23.58534, -46.44398 -23.5..."
4,242002000100,0.0,0.0,8aa81009a86ffff,"POLYGON ((-46.44440 -23.58552, -46.44454 -23.5..."

In [70]:
iptu_lotes_join_h3[iptu_lotes_join_h3['sqlc'] == '170041007100']

,sqlc,qnt_unidades_residencias,qnt_unidades_residencial_m2,id_hex,geometry
322261,170041007100,1.0,0.001569,8aa81005086ffff,"POLYGON ((-46.72412 -23.62563, -46.72417 -23.6..."

In [72]:
iptu_lotes_agg = iptu_lotes_join_h3.groupby(['id_hex']).agg({
    "qnt_unidades_residencias": ['sum', 'mean', 'median', 'std', 'var'],
}).reset_index()

In [75]:
iptu_lotes_agg[iptu_lotes_agg['id_hex'] == '8aa81005086ffff']

               id_hex qnt_unidades_residencias                             \
                                           sum      mean median       std
8565  8aa81005086ffff                40.890325  1.277823    1.0  2.206807


           var
8565  4.869996

:

In [56]:
iptu_lotes_agg.columns = ['_'.join(col).strip() for col in iptu_lotes_agg.columns.values if col != 'id_hex']

In [57]:
iptu_lotes_agg.head()

,id_hex_,qnt_unidades_residencias_sum,qnt_unidades_residencias_mean,qnt_unidades_residencias_median,qnt_unidades_residencias_std,qnt_unidades_residencias_var
0,8aa810000007fff,13.284450,0.531378,0.604773,0.444716,0.197772
1,8aa81000000ffff,2.147692,0.195245,0.000000,0.294814,0.086916
2,8aa810000017fff,5.925264,0.370329,0.126783,0.442388,0.195707
3,8aa81000001ffff,5.540030,0.461669,0.452016,0.416571,0.173531
4,8aa810000027fff,12.336361,0.560744,0.768548,0.456071,0.208000

In [58]:
iptu_lotes_agg[iptu_lotes_agg['id_hex_'] == '8aa8100c0747fff']

,id_hex_,qnt_unidades_residencias_sum,qnt_unidades_residencias_mean,qnt_unidades_residencias_median,qnt_unidades_residencias_std,qnt_unidades_residencias_var
20243,8aa8100c0747fff,1502.92053,46.966267,18.007929,58.99313,3480.189412

In [59]:
hex_iptu = hex_sp.join(iptu_lotes_agg.set_index('id_hex_'), how='left', on='id_hex')

In [60]:
hex_iptu["qnt_unidades_residencias_sum"] = np.ceil(hex_iptu["qnt_unidades_residencias_sum"])

In [61]:
hex_iptu.head()

,id_hex,geometry,qnt_unidades_residencias_sum,qnt_unidades_residencias_mean,qnt_unidades_residencias_median,qnt_unidades_residencias_std,qnt_unidades_residencias_var
0,8aa8100c3257fff,"POLYGON ((-46.63592 -23.53032, -46.63664 -23.5...",111.0,2.084064,0.000000,4.482464,20.092484
1,8aa8100d2447fff,"POLYGON ((-46.53650 -23.53972, -46.53722 -23.5...",108.0,1.374140,0.793144,6.736500,45.380426
2,8aa8100e1637fff,"POLYGON ((-46.66886 -23.59437, -46.66958 -23.5...",95.0,5.270948,0.000035,14.440480,208.527469
3,8aa8100f0827fff,"POLYGON ((-46.59115 -23.61353, -46.59187 -23.6...",0.0,0.000000,0.000000,NaN,NaN
4,8aa81010ec07fff,"POLYGON ((-46.65231 -23.83331, -46.65303 -23.8...",NaN,NaN,NaN,NaN,NaN

In [62]:
hex_iptu.fillna(0, inplace=True)

In [63]:
hex_iptu.isna().sum()

id_hex                             0
geometry                           0
qnt_unidades_residencias_sum       0
qnt_unidades_residencias_mean      0
qnt_unidades_residencias_median    0
qnt_unidades_residencias_std       0
qnt_unidades_residencias_var       0
dtype: int64

In [64]:
hex_iptu[hex_iptu['id_hex'] == '8aa8100c0747fff']

,id_hex,geometry,qnt_unidades_residencias_sum,qnt_unidades_residencias_mean,qnt_unidades_residencias_median,qnt_unidades_residencias_std,qnt_unidades_residencias_var
68073,8aa8100c0747fff,"POLYGON ((-46.62875 -23.55391, -46.62947 -23.5...",1503.0,46.966267,18.007929,58.99313,3480.189412

In [65]:

# Write the GeoDataFrame to a shapefile
hex_iptu.to_file("data/generate/WGS84_hex_iptu_2020.gpkg", driver="GPKG")